#-------------------------------
# General Site Settings

title: The Rat Cave | Discord Server
description: The Rat Cave is a fast-growing, tight-knit gaming community. We offer hosted lobbies for games ranging from Among Us to Minecraft. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://theratcavediscord.com" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name: vikkyc
author-avatar: vikkyc.png


#-------------------------------
# Contact links
spotify:  https://open.spotify.com/user/j0w6hqs23lpasaed9lhdy30m7 # Add your Spotify handle
twitter:   https://twitter.com/ # Add your Facebook handle
instagram: 
pinterest: 
discord: https://discord.gg/theratcave


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
#  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
